HomeworkBounty/config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
						 :controllers  => {
             :registrations => 'users/registrations',
           }
					 
	resources :questions do
		collection do
			get 'tags/:tag_list', as: :tags,to: :tags
		end
		collection do
			post 'search(/:category(/:tag_list))', as: :search,to: :search
		end
	end
					 
	
	resources :answers do
		resources :replies
		member do
			get 'accept', as: :accept, to: :accept_answer
		end
		member do
			get 'un_accept', as: :un_accept, to: :un_accept_answer
		end
	end
	resources :users, :only => [:show]
  root 'home#index'
	

end

HomeworkBounty/app/models/reply.rb
class Reply
  include Mongoid::Document
  field :body, type: String
	validates :body, :presence => true,
										:allow_blank =>false
  field :count, type: Integer
	field :author, type: String
	embedded_in :reply_to_answer, :class_name => 'Answer', :inverse_of => 'replies'
end

HomeworkBounty/app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
		@answer = Answer.find(params[:answer_id])
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
		answer = Answer.find(params[:answer_id])
    @reply = answer.replies.new(reply_params)
		@reply.author = current_user.username
		@reply.count = answer.replies.length
		
    respond_to do |format|
      if @reply.save
        format.html { redirect_to question_path(answer.question), notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to question_path(@answer.question), notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to question_path(@answer.question) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
			@answer = Answer.find(params[:answer_id])
      @reply = @answer.replies.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:body, :count)
    end
end

HomeworkBounty/app/helpers/replies_helper.rb
module RepliesHelper
end

HomeworkBounty/app/views/replies/_form.html.erb
<%= form_for [@answer,@reply] do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HomeworkBounty/app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', answer_reply_path(@answer,@reply) %> |
<%= link_to 'Back', question_path(@answer.question) %>

HomeworkBounty/app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer.replies.each do |reply| %>
      <% if (!current_user.nil?) && (reply.author == current_user.username)%>
				<tr>
					<td><%= reply.body %></td>
					<td><%= reply.count %></td>
					<td><%= link_to 'Show', answer_reply_path(@answer,reply)  %></td>
					<td><%= link_to 'Edit', edit_answer_reply_path(@answer,reply) %></td>
					<td><%= link_to 'Destroy', answer_reply_path(@answer,reply), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_answer_reply_path(@answer) %>

HomeworkBounty/app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_replies_path(@answer) %>

HomeworkBounty/app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @reply.body %>
</p>

<p>
  <strong>Count:</strong>
  <%= @reply.count %>
</p>

<%= link_to 'Edit', edit_answer_reply_path(@answer,@reply) %>
<%= link_to 'Back', question_path(@answer.question) %>