HomeworkBounty/config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
						 :controllers  => {
             :registrations => 'users/registrations',
           }
					 
	resources :questions do
		collection do
			get 'tags/:tag_list', as: :tags,to: :tags
		end
		collection do
			post 'search(/:category(/:tag_list))', as: :search,to: :search
		end
	end
					 
	
	resources :answers do
		resources :replies
		member do
			get 'accept', as: :accept, to: :accept_answer
		end
		member do
			get 'un_accept', as: :un_accept, to: :un_accept_answer
		end
	end
	resources :users, :only => [:show]
  root 'home#index'
	

end

HomeworkBounty/app/models/question.rb
class Question

  include Mongoid::Document
	include Mongoid::Timestamps
	include Mongoid::Slug
	include Mongoid::TagsArentHard
  field :title, type: String
	field :body, type: String
	field :url, type: String
	field :answered, type: Boolean, default:->{false}
	validates :title, :body, :presence => true,
										:allow_blank =>false
	#validates_uniqueness_of :title
	slug :title, history: true
	taggable_with :taglist
	
	
	#Belongs to a user
	belongs_to :author_to_question, :class_name => 'User', :inverse_of => 'questions_made'
	belongs_to :question_category, :class_name => 'Category', :inverse_of => 'questions_under_category'
	has_and_belongs_to_many :tags, :class_name => 'Tag', :inverse_of => 'questions'
	has_many :answers, :class_name => 'Answer', :inverse_of => 'question'


	def to_s
		"Question title #{title}, body #{body}"
	end
	
	
end

HomeworkBounty/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!, :except => [:tags, :index, :show]
	load_and_authorize_resource param_method: :question_params, :except => [:tags,:search]
	include QuestionsHelper


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
		author = User.find(current_user.username)
		@question = author.questions_made.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
	
	#Display /questions/tags
	def tags
		@question = Question.with_all_taglist(params[:tag_list])
	end
	
	#Display search on questions/search/
	def search
		if ( !params[:category]['question_category'].blank? &&  !params[:taglist].blank?)
			@tmp_question = Category.find(params[:category]['question_category']).questions_under_category
			@question =  @tmp_question.with_all_taglist(params[:taglist])
		elsif (!params[:taglist].blank?)
			@question =  Question.with_all_taglist(params[:taglist])
		elsif (!params[:category]['question_category'].blank?)
			@question = Category.find(params[:category]['question_category']).questions_under_category
		else	
			@question = Question.all
		end
	end
	
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
			params[:question].permit(:title, :body, :taglist, :question_category_id)
    end
end

HomeworkBounty/app/helpers/questions_helper.rb
module QuestionsHelper
#Get the most answered/ most popular questions
	def get_popular_questions
		Question.limit(10).sort_by {|q| q.answers.length}.reverse
	end

	def get_latest_questions
		Question.limit(10).order('created_at desc')
	end
	def get_tags_by_category
		tags = {}
		Category.each do |category|
			tags[category.name] = category.tags_under_category.pluck(:name)
		end
	end
	def can_reply_answer?(answer)
			if(current_user.nil?)
				return false
			elsif(answer.replies.length == 0) && (answer.author_to_answer.username != current_user.username)		
				return true
			else
				return false
			end
	end
	def can_reply?(answer,reply)
			if(current_user.nil?)
				return false
			elsif (reply.count == answer.replies.length) && (reply.author != current_user.username)
				return true
			else
				return false
			end
	end
	def can_accept(question,answer)
		if(current_user == question.author_to_question) && (answer.accepted?)
			return "unaccept"
		elsif(current_user == question.author_to_question) && (!answer.accepted?) && (!question.answered?)
			return "accept"
		else
			"hide"
		end
	end
	def can_answer?(question)
		if(current_user == question.author_to_question)	
			return false
		end
		question.answers.each do |answer|
			if(answer.author_to_answer == current_user)
				return false
			end
		end	
		return true
	end
end

HomeworkBounty/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
		<%= f.label :title %>
		<%= f.text_field :title %> <br />
		<%= f.label :body %>
		<%= f.text_area :body %> <br />
		<%= f.label :pick_category %>
		<%= f.collection_select :question_category_id, Category.all, :id, :name,prompt: true	 %>
		<%= f.label :add_tags %>
		<%= f.text_field :taglist %>
		<%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

HomeworkBounty/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

HomeworkBounty/app/views/questions/index.html.erb
<div class="newest_questions">
	<div class="search">
		<h3>Search questions</h3>
		<%= form_tag(search_questions_path(), method: "post") do %>
			<%= label_tag(:category, "Select category") %>
			<%= collection_select(:category, :question_category, Category.all, :id, :name, {include_blank: 'All categories'}) %>
			<%= label_tag(:taglist, "Tags") %>
			<%= text_field_tag(:taglist) %>
			<%= submit_tag("Search") %>
		<% end %>
	</div>
	<h3>Latest questions</h3>
	<div class="box shadow_effect">
		<% get_latest_questions.each do |question| %>
			<div class="answer_element_wrapper <%= cycle('even', 'odd') %>" >
				<% author = question.author_to_question %>
				<div class="question_body">
					<p class="question_title"><%= link_to question.title, question %></p>	
					<p><%= link_to author.username, user_path(author.username), :class => "user_name"  %></p>
					<p class="tag_list">
						<% question.taglist.each do |tag| %>
							<%= link_to tag,tags_questions_path(tag) %>
						<% end %>
					</p>
					<% if can? :update, question %>
						<p><%= link_to 'Edit', edit_question_path(question) %></p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
	<%= link_to 'New Question', new_question_path, :class => 'btn btn-default', :role => 'button' %>
</div>
<div class="newest_questions semi_questions">
	<h3>Popular questions</h3>

	<div class="box shadow_effect">
		<% get_popular_questions.each do |question| %>
			<div class="answer_element_wrapper <%= cycle('even', 'odd') %>" >
				<% author = question.author_to_question %>
				<div class="question_body">
					<p class="question_title"><%= link_to question.title, question %></p>	
					<p><%= link_to author.username, user_path(author.username), :class => "user_name"%></p>
					<% if can? :update, question %>
						<p class="edit"><%= link_to 'Edit', edit_question_path(question) %></p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

HomeworkBounty/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path, :class => 'btn btn-default', :role => 'button' %>

HomeworkBounty/app/views/questions/search.html.erb
<div class="newest_questions">
	
	<h3>Questions by search</h3>
	<div class="box shadow_effect">
		<% @question.each do |question| %>
			<div class="answer_element_wrapper <%= cycle('even', 'odd') %>" >
				<% author = question.author_to_question %>
				<div class="question_body">
					<p class="question_title"><%= link_to question.title, question %></p>	
					<p><%= link_to author.username, user_path(author.username), :class => "user_name"  %></p>
					<p class="tag_list">
						<% question.taglist.each do |tag| %>
							<%= link_to tag,tags_questions_path(tag) %>
						<% end %>
					</p>
					<% if can? :update, question %>
						<p><%= link_to 'Edit', edit_question_path(question) %></p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

HomeworkBounty/app/views/questions/show.html.erb
<div class="new_answer_wrapper">
	<div class="answer_header_wrapper">
		<div class="answer_header">
			<h3>
				<%= @question.title %>
			</h3>
		</div>
		<div class="answer_buttons">
			<% if can_answer?(@question) %>
				<%= link_to 'Answer question', '#', :id => "answer_btn", :class => 'btn btn-default', :role => 'button' %>
			<% end %>	
			<% if can? :destroy, @question %>
				<%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
			<%= link_to 'Back', questions_path, :class => 'btn btn-default', :role => 'button' %>
		</div>
	</div>


	<div class="box shadow_effect">
		<div class="answer_element_wrapper odd" >
			<% author = @question.author_to_question %>
			<div class="posted_by">
				<div class="user_image"><%= image_tag avatar_url(author)%></div>
				<p><%= link_to author.username, user_path(author.username) %></p>
				<p>Answers: <%= author.answers_made.size %></p>
			</div>


			<div class="answer_body">
				<p><%= @question.body %></p>
				<% if can? :update, @question %>
					<%= link_to 'Edit', edit_question_path(@question) %>
				<% end %>
			</div>
		</div>

		<% @question.answers.each do |answer| %>
			<div class="answer_element_wrapper <%= cycle('even', 'odd') %>" >
				<% author = answer.author_to_answer %>
				<div class="posted_by">
					<div class="user_image"><%= image_tag avatar_url(author)%></div>
					<p><%= link_to author.username, user_path(author.username) %></p>
					<p>Answers: <%= author.answers_made.size %></p>
				</div>


				<div class="answer_body">
					<p><%= answer.body %></p>
					<% if can_reply_answer?(answer)%>
							<%= link_to 'reply', answer_replies_path(answer), :class => 'reply_btn btn btn-default', :value => answer._id %>
					<% end %>
					<% if can? :update, answer %>
						<%= link_to 'Edit', edit_answer_path(answer),:class => 'edit_button btn btn-default' %>
					<% end %>
					<% can_accept_answer = can_accept(@question,answer) %>
					<% if can_accept_answer == "accept"%>
							<%= link_to 'Accept', accept_answer_path(answer), :class => 'accept_btn btn btn-default' %>
					<% elsif can_accept_answer == "unaccept" %>
						<%= link_to 'Un accept', un_accept_answer_path(answer), :class => 'accept_btn btn btn-default' %>	
					<% end %>
				</div>
			</div>
			<% answer.replies.each do |reply| %>
				<div class="reply_element_wrapper <%= cycle('even', 'odd') %>" >
					<% author = reply.author %>
					<div class="posted_by">
						<div class="user_image"><%= image_tag avatar_url(author)%></div>
						<p><%= link_to author, user_path(author) %></p>
					</div>
					<div class="reply_body">
						<p><%= reply.body %></p>
						<% if can_reply?(answer,reply)%>
							<%= link_to 'Reply', answer_replies_path(answer), :class => 'reply_btn btn btn-default', :value => answer._id %>
						<% end %>
						<% if can? :update, reply %>
							<%= link_to 'Edit', edit_answer_reply_path(answer,reply), :class => 'edit_button 	btn btn-default' %>
						<% end %>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

<div id="answer_form_container">
	<%= form_tag("/answers", method: "post") do %>
		<%= label(:answer, :body, "New answer") %>
		<%= text_area(:answer, :body) %>
		<%= hidden_field(:answer, :question,:value => @question._id) %>
		<%= submit_tag("New answer", :class => 'btn btn-default') %>
	<% end %>
</div>
<div id="answer_reply_form_container">
	<%= form_tag("/answers/reply", method: "post") do %>
		<%= label(:reply, :body, "New reply") %>
		<%= text_area(:reply, :body) %>
		<%= submit_tag("New reply", :class => 'btn btn-default') %>
	<% end %>
</div>

HomeworkBounty/app/views/questions/tags.html.erb
<div class="newest_questions">
	
	<h3>Questions by tag</h3>
	<div class="box shadow_effect">
		<% @question.each do |question| %>
			<div class="answer_element_wrapper <%= cycle('even', 'odd') %>" >
				<% author = question.author_to_question %>
				<div class="question_body">
					<p class="question_title"><%= link_to question.title, question %></p>	
					<p><%= link_to author.username, user_path(author.username), :class => "user_name"  %></p>
					<p class="tag_list">
						<% question.taglist.each do |tag| %>
							<%= link_to tag,tags_questions_path(tag) %>
						<% end %>
					</p>
					<% if can? :update, question %>
						<p><%= link_to 'Edit', edit_question_path(question) %></p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>